### PR TITLE
Fixing HF inconsistencies

### LINKED ISSUE #840: Rewrite UHF using USQHamiltonian
There has been an oversight in the previous refactors: we're still using `RSQHamiltonian` in the `hamiltonian` field in `UHFSCFEnvironment`.

### LINKED ISSUE #845: Change overlap argument in HF modules
There are still some minor inconsistencies between the HF modules.

A large part of them are written using the correct one-electron operators, but the 'overlap matrix' is required as an argument for the environments.

It would be better if we changed this to `R/U/GSQOneElectronOperator` instead of `SquareMatrix`.

### PR DESCRIPTION
**Pull request by xdvriend**
**Short description**
The UHF `QCMethod` was still written using an `RSQHamiltonian`. his PR changes that. Now all HF methods use their own Hamiltonian.

Since there is another inconsistency regarding the overlap matrix, which should be an operator, I'll tackle that here as well.

**Related issues**
closes #840 
closes #845 

**Additional context**
I have also updated the python bindings and updated the example notebooks that use UHF calculations. They are now up to date with the latest python bindings. 

**Don't forget:**
- [x] if new files are created: update the Doxygen file, the collective gqcp.hpp header and the CMake files

### CODE REVIEW

File: gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_stability_test.cpp [hunk 1]
```diff
@@ -87,10 +85,10 @@ BOOST_AUTO_TEST_CASE(H4_stability_test) {
     const auto N_alpha = molecule.numberOfElectronPairs();
     const auto N_beta = molecule.numberOfElectronPairs();
 
-    const GQCP::RSpinOrbitalBasis<double, GQCP::GTOShell> spinor_basis {molecule, "6-31G"};
-    const auto S = spinor_basis.overlap().parameters();
+    const GQCP::USpinOrbitalBasis<double, GQCP::GTOShell> spinor_basis {molecule, "6-31G"};
+    const auto S = spinor_basis.overlap().alpha().parameters();
```
Comment (lelemmen) [inline gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_stability_test.cpp:89]:
```suggestion
    const auto S = spinor_basis.overlap().alpha().parameters();  // The alpha and beta overlap matrices are equal.
```

File: gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_test.cpp [hunk 2]
```diff
@@ -56,10 +56,10 @@ BOOST_AUTO_TEST_CASE(h2o_sto3g_plain) {
     const auto N_alpha = water.numberOfElectronPairs();
     const auto N_beta = water.numberOfElectronPairs();
 
-    const GQCP::RSpinOrbitalBasis<double, GQCP::GTOShell> spinor_basis {water, "STO-3G"};
-    const auto sq_hamiltonian = GQCP::RSQHamiltonian<double>::Molecular(spinor_basis, water);  // in an AO basis
+    const GQCP::USpinOrbitalBasis<double, GQCP::GTOShell> spinor_basis {water, "STO-3G"};
+    const auto sq_hamiltonian = GQCP::USQHamiltonian<double>::Molecular(spinor_basis, water);  // in an AO basis
 
-    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_alpha, N_beta, sq_hamiltonian, spinor_basis.overlap().parameters());
+    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_alpha, N_beta, sq_hamiltonian, spinor_basis.overlap().alpha().parameters());
```
Comment (lelemmen) [inline gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_test.cpp:62]:
```suggestion
    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_alpha, N_beta, sq_hamiltonian, spinor_basis.overlap().alpha().parameters());  // The alpha and beta overlap matrices are equal.
```

File: gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_test.cpp [hunk 3]
```diff
@@ -104,10 +104,10 @@ BOOST_AUTO_TEST_CASE(h2o_sto3g_diis) {
...
```
Comment (lelemmen) [inline gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_test.cpp:110]:
```suggestion
    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_alpha, N_beta, sq_hamiltonian, spinor_basis.overlap().alpha().parameters());  // The alpha and beta overlap matrices are equal.
```

File: gqcp/tests/QCModel/HF/UHF_test.cpp [hunk 4]
```diff
@@ -106,23 +106,22 @@ BOOST_AUTO_TEST_CASE(UHF_DMs) {
...
     const auto molecule = GQCP::Molecule::ReadXYZ("data/h2o.xyz");
-    const GQCP::RSpinOrbitalBasis<double, GQCP::GTOShell> spin_orbital_basis {molecule, "STO-3G"};
-    auto r_hamiltonian = GQCP::RSQHamiltonian<double>::Molecular(spin_orbital_basis, molecule);  // In an AO basis.
+    const GQCP::USpinOrbitalBasis<double, GQCP::GTOShell> u_spin_orbital_basis {molecule, "STO-3G"};
+    auto hamiltonian = GQCP::USQHamiltonian<double>::Molecular(u_spin_orbital_basis, molecule);  // In an AO basis.
 
     const auto N_a = molecule.numberOfElectronPairs();  // The number of alpha electrons.
     const auto N_b = molecule.numberOfElectronPairs();  // The number of beta electrons.
-    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_a, N_b, r_hamiltonian, spin_orbital_basis.overlap().parameters());
+    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_a, N_b, hamiltonian, u_spin_orbital_basis.overlap().alpha().parameters());
```
Comment (lelemmen) [inline gqcp/tests/QCModel/HF/UHF_test.cpp:114]:
```suggestion
    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_a, N_b, hamiltonian, u_spin_orbital_basis.overlap().alpha().parameters());  // The alpha and beta overlap matrices are equal.
```

**Review by lelemmen — APPROVED** [review]
I see now that the UHF module (before this PR) was apparently neglected in the R/U/G refactors #742. I've also opened #845 to address another inconsistency.

Despite the many "suggestions", this PR is great! My eye caught some small documentation that wasn't adjusted for our new style, so I've proposed the changes.

**Comment by xdvriend** [comment]
> I see now that the UHF module (before this PR) was apparently neglected in the R/U/G refactors #742. I've also opened #845 to address another inconsistency.

Yes, I saw it. I'll adjust that in this PR as well. Since I'm adding something extra, I'll be sure to re-request a review once it's finished.

> Despite the many "suggestions", this PR is great! My eye caught some small documentation that wasn't adjusted for our new style, so I've proposed the changes.

Ah good catch! I didn't think of fixing the outdated documentation, so thanks for that!

**Comment by xdvriend** [comment]
@lelemmen I have re-requested your review on this PR. I changed quite a bit since the last time, so here's a summary:

- I fixed a lot (hopefully all) of the documentation in the HF `QCModel`s and `QCMethod`s.
- I fixed the inconsistency with S, each HF method now uses its respective S-operator.
- I made it so the UHF Environment only contains spin resolved objects.
- I adjusted the python bindings to accommodate these changes.
- I updated the notebooks to use the new python bindings.

Some of the python bindings in the HF `QCMethods` can be seriously revamped in my opinion. I was thinking on tackling that refactor when I implement the RHF and UHF complex bindings.

File: gqcp/include/QCMethod/HF/GHF/GHFDensityMatrixCalculation.hpp [hunk 5]
```diff
@@ -55,11 +55,13 @@ class GHFDensityMatrixCalculation:
     /**
      *  Calculate the current GHF density matrix and place it in the environment.
      * 
-     *  @param environment              the environment that acts as a sort of calculation space
+     *  @param environment              The environment that acts as a sort of calculation space.
      */
     void execute(Environment& environment) override {
+
         const auto& C = environment.coefficient_matrices.back();  // the most recent coefficient matrix
```
Comment (lelemmen) [inline gqcp/include/QCMethod/HF/GHF/GHFDensityMatrixCalculation.hpp:62]:
```suggestion
        const auto& C = environment.coefficient_matrices.back();  // The most recent coefficient matrix.
```

File: gqcp/include/QCMethod/HF/GHF/GHFFockMatrixCalculation.hpp [hunk 6]
```diff
@@ -56,11 +56,13 @@ class GHFFockMatrixCalculation:
     /**
      *  Calculate the current GHF Fock matrix (expressed in the scalar/AO basis) and place it in the environment.
      * 
-     *  @param environment              the environment that acts as a sort of calculation space
+     *  @param environment              The environment that acts as a sort of calculation space.
      */
     void execute(Environment& environment) override {
+
         const auto& P = environment.density_matrices.back();  // the most recent density matrix
```
Comment (lelemmen) [inline gqcp/include/QCMethod/HF/GHF/GHFFockMatrixCalculation.hpp:63]:
```suggestion
        const auto& P = environment.density_matrices.back();  // The most recent density matrix.
```

File: gqcp/include/QCMethod/HF/UHF/UHFFockMatrixDIIS.hpp [hunk 7]
```diff
@@ -107,13 +106,21 @@ class UHFFockMatrixDIIS:
...
+        for (size_t i = 0; i < error_vectors.size(); i++) {
+            alpha_error_vectors.push_back(error_vectors[i].alpha());
+            beta_error_vectors.push_back(error_vectors[i].beta());
+        }
+
         // Calculate the accelerated Fock matrices and do a diagonalization step on them.
-        const auto F_alpha_accelerated = this->diis.accelerate(alpha_fock_matrices, error_vectors_alpha);
-        const auto F_beta_accelerated = this->diis.accelerate(beta_fock_matrices, error_vectors_alpha);
+        const auto F_alpha_accelerated = this->diis.accelerate(alpha_fock_matrices, alpha_error_vectors);
+        const auto F_beta_accelerated = this->diis.accelerate(beta_fock_matrices, beta_error_vectors);
```
Comment (lelemmen) [inline gqcp/include/QCMethod/HF/UHF/UHFFockMatrixDIIS.hpp:119]: Yikes! Thanks for fixing this (unnoticed) bug.

File: gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_stability_test.cpp [hunk 8]
```diff
@@ -39,7 +39,7 @@ BOOST_AUTO_TEST_CASE(H3_stability_test) {
     const auto N_beta = molecule.numberOfElectronPairs();
 
     const GQCP::USpinOrbitalBasis<double, GQCP::GTOShell> spinor_basis {molecule, "STO-3G"};
-    const auto S = spinor_basis.overlap().alpha().parameters();
+    const auto S = spinor_basis.overlap();  // The alpha and beta overlap matrices are equal.
```
Comment (lelemmen) [inline gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_stability_test.cpp:42]:
```suggestion
    const auto S = spinor_basis.overlap();
```

I think I initially suggested this documentation in order to explain why we only took the 'alpha' overlap matrix. Since the API has changed, this isn't necessary anymore!

File: gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_stability_test.cpp [hunk 9]
```diff
@@ -86,7 +86,7 @@ BOOST_AUTO_TEST_CASE(H4_stability_test) {
     const auto N_beta = molecule.numberOfElectronPairs();
 
     const GQCP::USpinOrbitalBasis<double, GQCP::GTOShell> spinor_basis {molecule, "6-31G"};
-    const auto S = spinor_basis.overlap().alpha().parameters();
+    const auto S = spinor_basis.overlap();  // The alpha and beta overlap matrices are equal.
```
Comment (lelemmen) [inline gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_stability_test.cpp:89]:
```suggestion
    const auto S = spinor_basis.overlap();
```

File: gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_test.cpp [hunk 10]
```diff
@@ -57,19 +57,19 @@ BOOST_AUTO_TEST_CASE(h2o_sto3g_plain) {
     const auto N_beta = water.numberOfElectronPairs();
 
     const GQCP::USpinOrbitalBasis<double, GQCP::GTOShell> spinor_basis {water, "STO-3G"};
-    const auto sq_hamiltonian = GQCP::USQHamiltonian<double>::Molecular(spinor_basis, water);  // in an AO basis
+    const auto sq_hamiltonian = GQCP::USQHamiltonian<double>::Molecular(spinor_basis, water);  // In an AO basis.
 
-    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_alpha, N_beta, sq_hamiltonian, spinor_basis.overlap().alpha().parameters());
+    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_alpha, N_beta, sq_hamiltonian, spinor_basis.overlap());  // The alpha and beta overlap matrices are equal.
```
Comment (lelemmen) [inline gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_test.cpp:62]:
```suggestion
    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_alpha, N_beta, sq_hamiltonian, spinor_basis.overlap());
```

File: gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_test.cpp [hunk 11]
```diff
@@ -105,19 +105,19 @@ BOOST_AUTO_TEST_CASE(h2o_sto3g_diis) {
...
```
Comment (lelemmen) [inline gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_test.cpp:110]:
```suggestion
    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_alpha, N_beta, sq_hamiltonian, spinor_basis.overlap());
```

File: gqcp/tests/QCModel/HF/UHF_test.cpp [hunk 12]
```diff
@@ -109,9 +109,9 @@ BOOST_AUTO_TEST_CASE(UHF_DMs) {
     const GQCP::USpinOrbitalBasis<double, GQCP::GTOShell> u_spin_orbital_basis {molecule, "STO-3G"};
     auto hamiltonian = GQCP::USQHamiltonian<double>::Molecular(u_spin_orbital_basis, molecule);  // In an AO basis.
 
-    const auto N_a = molecule.numberOfElectronPairs();  // The number of alpha electrons.
-    const auto N_b = molecule.numberOfElectronPairs();  // The number of beta electrons.
-    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_a, N_b, hamiltonian, u_spin_orbital_basis.overlap().alpha().parameters());
+    const auto N_a = molecule.numberOfElectronPairs();                                                                             // The number of alpha electrons.
+    const auto N_b = molecule.numberOfElectronPairs();                                                                             // The number of beta electrons.
+    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_a, N_b, hamiltonian, u_spin_orbital_basis.overlap());  // The alpha and beta overlap matrices are equal.
```
Comment (lelemmen) [inline gqcp/tests/QCModel/HF/UHF_test.cpp:114]:
```suggestion
    auto uhf_environment = GQCP::UHFSCFEnvironment<double>::WithCoreGuess(N_a, N_b, hamiltonian, u_spin_orbital_basis.overlap());
```

File: gqcpy/src/QCMethod/HF/GHF/GHFSCFEnvironment_bindings.cpp [hunk 13]
```diff
@@ -53,9 +53,9 @@ void bindQCModelGHFSCFEnvironmentInterface(Class& py_class) {
 
         .def_static(
             "WithCoreGuess",
-            [](const size_t N, const GSQHamiltonian<Scalar>& hamiltonian, const Eigen::Matrix<Scalar, Eigen::Dynamic, Eigen::Dynamic>& S) {
+            [](const size_t N, const GSQHamiltonian<Scalar>& hamiltonian, const ScalarGSQOneElectronOperator<Scalar>& S) {
                 // Use an itermediary Eigen matrix for the Python binding, since Pybind11 doesn't accept our types that are derived from Eigen::Matrix.
```
Comment (lelemmen) [inline gqcpy/src/QCMethod/HF/GHF/GHFSCFEnvironment_bindings.cpp:57]:
```suggestion
```

File: gqcpy/src/QCMethod/HF/GHF/GHFSCFEnvironment_bindings.cpp [hunk 14]
```diff
@@ -75,9 +75,9 @@ void bindQCModelGHFSCFEnvironmentInterface(Class& py_class) {
             [](const GHFSCFEnvironment<Scalar>& environment) {
                 return environment.S;
             },
-            [](GHFSCFEnvironment<Scalar>& environment, const Eigen::Matrix<Scalar, Eigen::Dynamic, Eigen::Dynamic>& S) {
+            [](GHFSCFEnvironment<Scalar>& environment, ScalarGSQOneElectronOperator<Scalar>& S) {
                 // Use an itermediary Eigen matrix for the Python binding, since Pybind11 doesn't accept our types that are derived from Eigen::Matrix.
```
Comment (lelemmen) [inline gqcpy/src/QCMethod/HF/GHF/GHFSCFEnvironment_bindings.cpp:79]:
```suggestion
```

File: gqcpy/src/QCMethod/HF/GHF/GHFSCFEnvironment_bindings.cpp [hunk 15]
```diff
@@ -75,9 +75,9 @@ void bindQCModelGHFSCFEnvironmentInterface(Class& py_class) {
...
-                environment.S = SquareMatrix<Scalar>(S);
+                environment.S = ScalarGSQOneElectronOperator<Scalar>(S);
```
Comment (lelemmen) [inline gqcpy/src/QCMethod/HF/GHF/GHFSCFEnvironment_bindings.cpp:80]:
```suggestion
                environment.S = S;
```

File: gqcpy/src/QCMethod/HF/RHF/RHFSCFEnvironment_bindings.cpp [hunk 16]
```diff
@@ -55,7 +55,7 @@ void bindRHFSCFEnvironment(py::module& module) {
                 return environment.S;
             },
             [](RHFSCFEnvironment<double>& environment, const Eigen::MatrixXd& S) {
```
Comment (lelemmen) [inline gqcpy/src/QCMethod/HF/RHF/RHFSCFEnvironment_bindings.cpp:57]:
```suggestion
            [](RHFSCFEnvironment<double>& environment, const ScalarRSQOneElectronOperator<double>& S) {
```

File: gqcpy/src/QCMethod/HF/RHF/RHFSCFEnvironment_bindings.cpp [hunk 17]
```diff
@@ -55,7 +55,7 @@ void bindRHFSCFEnvironment(py::module& module) {
...
-                environment.S = SquareMatrix<double>(S);
+                environment.S = ScalarRSQOneElectronOperator<double>(S);
```
Comment (lelemmen) [inline gqcpy/src/QCMethod/HF/RHF/RHFSCFEnvironment_bindings.cpp:58]:
```suggestion
                environment.S = S;
```

File: gqcp/include/QCMethod/HF/UHF/UHFSCFEnvironment.hpp [hunk 18]
```diff
@@ -78,16 +75,15 @@ class UHFSCFEnvironment {
...
+     *  @param N_beta                   The number of beta electrons (the number of occupied beta-spin-orbitals).
+     *  @param sq_hamiltonian           The Hamiltonian expressed in the scalar (AO) basis.
+     *  @param S                        The overlap matrix (of the scalar (AO) basis).
      *  @param C_alpha_initial          The initial coefficient matrix for the alpha spin-orbitals.
      *  @param C_beta_initial           The initial coefficient matrix for the beta spin-orbitals.
      */
-    UHFSCFEnvironment(const size_t N_alpha, const size_t N_beta, const USQHamiltonian<Scalar>& sq_hamiltonian, const SquareMatrix<Scalar>& S, const UTransformationComponent<Scalar>& C_alpha_initial, const UTransformationComponent<Scalar>& C_beta_initial) :
-        N_alpha {N_alpha},
-        N_beta {N_beta},
+    UHFSCFEnvironment(const size_t N_alpha, const size_t N_beta, const USQHamiltonian<Scalar>& sq_hamiltonian, const ScalarUSQOneElectronOperator<Scalar>& S, const UTransformationComponent<Scalar>& C_alpha_initial, const UTransformationComponent<Scalar>& C_beta_initial) :
```
Comment (lelemmen) [inline gqcp/include/QCMethod/HF/UHF/UHFSCFEnvironment.hpp:85]: Perhaps we could also 
```suggestion
    UHFSCFEnvironment(const size_t N_alpha, const size_t N_beta, const USQHamiltonian<Scalar>& sq_hamiltonian, const ScalarUSQOneElectronOperator<Scalar>& S, const UTransformation<Scalar>& C_initial) :
```

Perhaps we could also change from the 2 arguments to the 1 encapsulating argument? (This also applies to the Python bindings.)

File: gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp [hunk 19]
```diff
@@ -56,28 +56,26 @@ void bindUHFSCFEnvironment(py::module& module) {
...
 
         .def_property(
             "S",
             [](const UHFSCFEnvironment<double>& environment) {
                 return environment.S;
             },
-            [](UHFSCFEnvironment<double>& environment, const Eigen::MatrixXd& S) {
-                environment.S = SquareMatrix<double>(S);
+            [](UHFSCFEnvironment<double>& environment, const ScalarUSQOneElectronOperator<double>& S) {
+                environment.S = ScalarUSQOneElectronOperator<double>(S);
```
Comment (lelemmen) [inline gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp:78]:
```suggestion
                environment.S = S;
```

File: gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp [hunk 20]
```diff
@@ -56,28 +56,26 @@ void bindUHFSCFEnvironment(py::module& module) {
...
         // Bind read-write members/properties, exposing intermediary environment variables to the Python interface.
-        .def_readwrite("N_alpha", &UHFSCFEnvironment<double>::N_alpha)
-        .def_readwrite("N_beta", &UHFSCFEnvironment<double>::N_beta)
+        .def_readwrite("N", &UHFSCFEnvironment<double>::N)
 
         .def_readwrite("electronic_energies", &UHFSCFEnvironment<double>::electronic_energies)
 
-        .def_readwrite("orbital_energies_alpha", &UHFSCFEnvironment<double>::orbital_energies_alpha)
-        .def_readwrite("orbital_energies_beta", &UHFSCFEnvironment<double>::orbital_energies_beta)
+        .def_readwrite("orbital_energies", &UHFSCFEnvironment<double>::orbital_energies)
```
Comment (lelemmen) [inline gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp:70]: Does this also require a Python binding for `SpinResolved<...>`?

File: gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp [hunk 21]
```diff
@@ -204,14 +199,22 @@ void bindUHFSCFEnvironment(py::module& module) {
...
              [](UHFSCFEnvironment<double>& environment, const Eigen::MatrixXd& new_error_vectors_beta) {
-                 environment.error_vectors_beta.pop_back();
-                 environment.error_vectors_beta.push_back(SquareMatrix<double>(new_error_vectors_beta));
+                 const auto last_spinResolved_error = environment.error_vectors.back();
+                 const auto last_error_vector_alpha = last_spinResolved_error.alpha();
+                 SpinResolved<VectorX<double>> new_error {last_error_vector_alpha, new_error_vectors_beta};
+
+                 environment.error_vectors.pop_back();
+                 environment.error_vectors.push_back(new_error);
              });
```
Comment (lelemmen) [inline gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp:218]: In line of the spin-resolved types: I would suggest to change this into only providing `.def("replace_current_error_vectors")`. I think it's OK to ask the user to replace either (or both) of the `SpinResolved<...>` components and then push these changes to the environment.

**Review by lelemmen — APPROVED** [review]
Thanks for the additional work that happened in this PR. It's very much appreciated! I'm aware that updating documentation is a chore, and I'm also very happy with the 'unrestricted' spin-resolved changes). The updated files look really fresh!👍🏻 

I've added a couple more suggestions, but I trust that you can resolve them without an additional review. Great job!!!

File: gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp (hunk 20 above)
Comment (xdvriend) [reply gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp:70]: It does, but I believe `SpinResolved<VectorX<double>>` already has a binding. I could be mistaken and I'll be sure to check before merging this PR!

Comment (lelemmen) [reply gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp:70]: Ok, I didn't remember.

**Comment by xdvriend** [comment]
@lelemmen, I have adjusted the `replace_`API's in the python bindings in order to take two arguments and replace "all" matrices/parameters of that instance. 

Since you mentioned on MS teams that you wanted to review that, I'll leave this PR unmarked until you do. The examples are removed due to a conflict with the develop branch, But I will update the Hartree Fock notebooks with the new bindings in my next PR.

File: gqcp/include/QCMethod/HF/UHF/UHFSCFEnvironment.hpp [hunk 22]
```diff
@@ -99,7 +99,7 @@ class UHFSCFEnvironment {
     UHFSCFEnvironment(const QCModel::RHF<Scalar>& rhf_parameters, const USQHamiltonian<Scalar>& sq_hamiltonian, const ScalarUSQOneElectronOperator<Scalar>& S) :
         UHFSCFEnvironment(rhf_parameters.numberOfElectrons(Spin::alpha), rhf_parameters.numberOfElectrons(Spin::beta),
                           sq_hamiltonian, S,
-                          rhf_parameters.expansion().matrix(), rhf_parameters.expansion().matrix()) {}
+                          UTransformation<Scalar> {rhf_parameters.expansion().matrix(), rhf_parameters.expansion().matrix()}) {}
```
Comment (lelemmen) [inline gqcp/include/QCMethod/HF/UHF/UHFSCFEnvironment.hpp:102]: There's a short-hand named constructor for this:
```suggestion
                          UTransformation<Scalar>::FromEqual(rhf_parameters.expansion().matrix())) {}
```

File: gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp [hunk 23]
```diff
@@ -35,15 +35,14 @@ void bindUHFSCFEnvironment(py::module& module) {
 
         // CONSTRUCTORS
 
-        .def(py::init([](const size_t N_alpha, const size_t N_beta, const USQHamiltonian<double>& sq_hamiltonian, const ScalarUSQOneElectronOperator<double>& S, const Eigen::MatrixXd& C_alpha_initial, const Eigen::MatrixXd& C_beta_initial) {
-                 return UHFSCFEnvironment<double>(N_alpha, N_beta, sq_hamiltonian, S, UTransformationComponent<double>(C_alpha_initial), UTransformationComponent<double>(C_beta_initial));
+        .def(py::init([](const size_t N_alpha, const size_t N_beta, const USQHamiltonian<double>& sq_hamiltonian, const ScalarUSQOneElectronOperator<double>& S, const UTransformation<double>& C_initial) {
+                 return UHFSCFEnvironment<double>(N_alpha, N_beta, sq_hamiltonian, S, UTransformation<double>(C_initial));
```
Comment (lelemmen) [inline gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp:39]:
```suggestion
                 return UHFSCFEnvironment<double>(N_alpha, N_beta, sq_hamiltonian, S, C_initial);
```

**Review by lelemmen — APPROVED** [review]
I'm thinking of something: didn't you also update some notebooks for updated Python bindings? Did the removal from the `gqcpy/examples/` folder cause any loss of implementations?

Thanks for the additional maintenance work during this PR: the UHF environment's bindings look a lot better in my opinion. Good job!

**Comment by xdvriend** [comment]
> I'm thinking of something: didn't you also update some notebooks for updated Python bindings? Did the removal from the `gqcpy/examples/` folder cause any loss of implementations?

Some updates I provided did indeed get removed, but I saved the updated notebooks. So we didn't lose any implementations. It will take me almost no time to fix these notebooks in a subsequent PR. :smile:

> Thanks for the additional maintenance work during this PR: the UHF environment's bindings look a lot better in my opinion. Good job!

Thank you & no problem!
