### PR TITLE
Re-enable benchmarks

### LINKED ISSUE #725: Enable the evaluation of `RSQOperators` in a seniority-zero ONV basis
In recent refactors (#688), we had to temporarily disable some of the CI functionality. This issue tracks the re-enabling of the API to evaluate restricted operators in a seniority-zero ONV basis.

- [x] One-electron;
- [x] Two-electron;
- [x] Hamiltonian;

- [x] Re-enable the corresponding test in `LinearExpansion_test`.

### LINKED ISSUE #744: Re-enable benchmarks
In #707, I had to disable the benchmarks from the CI workflow. They should be re-enabled.

### LINKED ISSUE #773: Re-enable Hubbard calculations
These were disabled after #707.

### LINKED ISSUE #833: Simple2DM_test failing in Conda linux builds.
**Describe the bug**
Conda builds on Linux have one test failing
```
17/85 Test #17: Simple2DM_test .................................***Failed    0.06 sec
Running 3 test cases...
Will read basis set from $PREFIX/share/libint/2.4.2/basis/sto-3g.g94
$SRC_DIR/gqcp/tests/DensityMatrix/Simple2DM_test.cpp(137): error: in "two_electron_operator_expectation_value_different_orbital_bases": check std::abs(exp_val_AO - exp_val_random) < 1.0e-12 has failed

*** 1 failure is detected in the test module "Simple2DM"
```

**To Reproduce**
Consult CI for commit c1f88dc in PR #831.

### PR DESCRIPTION
**Pull request by lelemmen**
This PR will re-enable all benchmarks:
- [x] I also fixed a failing test (closes #833);
- [x] Closes #773;
- [x] Closes #744;
- [x] Closes #725.

**Don't forget:**
- [x] if new files are created: update the Doxygen file, the collective gqcp.hpp header and the CMake files

### CODE REVIEW

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 1]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
+
+            while (q < K) {
+                const size_t J = address + proxy_onv_basis.vertexWeight(q, e2);
+
+                H(I, J) += g(p, q, p, q);
+                H(J, I) += g(p, q, p, q);
+
+                q++;  // go to the next orbital
+
+                // perform a shift  TODO: clarify what shift
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:141]:
```suggestion
                // Perform a shift;  TODO: clarify what shift.
```

Same question as before. If it's on purpose, ignore this 😄

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 2]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
+                proxy_onv_basis.shiftUntilNextUnoccupiedOrbital<1>(onv, address, q, e2);
+            }  // creation
+        }      // e1 loop (annihilation)
+
+        if (I < dim - 1) {  // prevent the last permutation from occurring
+            proxy_onv_basis.transformONVToNextPermutation(onv);
+        }
+    }  // address (I) loop
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:149]:
```suggestion
            }  // Creation.
        }      // E1 loop (annihilation).

        if (I < dim - 1) {  // Prevent the last permutation from occurring.
            proxy_onv_basis.transformONVToNextPermutation(onv);
        }
    }  // Address (I) loop.
```

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 3]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
-//         });
+    // Iterate over every proxy doubly-occupied ONV. Since we are actually using spin-unresolved ONVs, we should multiply contributions by 2.
+    this->forEach([&diagonal, &f](const SpinUnresolvedONV& onv, const size_t I) {
+        double value = 0;  // to be added to the diagonal
 
-//         diagonal(I) += value;
-//     });
+        // Loop over every occupied orbital index and add the contribution.
+        onv.forEach([&value, &f](const size_t p) {
+            value += 2 * f(p, p);  // *2 because of seniority-zero
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:186]:
```suggestion
            value += 2 * f(p, p);  //Factor  *2 because of seniority-zero.
```

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 4]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
+    this->forEach([&diagonal, &g](const SpinUnresolvedONV& onv, const size_t I) {
+        double value = 0;  // to be added to the diagonal
 
-//         // Loop over every occupied spinor index and add the contributions.
-//         onv.forEach([&value, &g](const size_t p) {
-//             value += g(p, p, p, p);  // 1/2*2 because of seniority-zero
-//         });
+        // Loop over every occupied spinor index and add the contributions.
+        onv.forEach([&value, &g](const size_t p) {
+            value += g(p, p, p, p);  // 1/2*2 because of seniority-zero
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:223]:
```suggestion
            value += g(p, p, p, p);  // Factor 1/2*2 because of seniority-zero.
```

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 5]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
+VectorX<double> SeniorityZeroONVBasis::evaluateOperatorDiagonal(const RSQHamiltonian<double>& hamiltonian) const {
 
-//     // We don't just use the sum of the one- and two-electron operator's diagonal representation because that would mean 2 iterations over the dimension of the ONV basis.
+    // We don't just use the sum of the one- and two-electron operator's diagonal representation because that would mean 2 iterations over the dimension of the ONV basis.
 
 
-//     // Check if the argument is compatible.
-//     const auto K = sq_hamiltonian.numberOfOrbitals();  // number of spatial orbitals
+    // Check if the argument is compatible.
+    const auto K = hamiltonian.numberOfOrbitals();  // number of spatial orbitals
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:252]:
```suggestion
    const auto K = hamiltonian.numberOfOrbitals();  // The number of spatial orbitals.
```

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 6]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
 
-//         // Loop over every occupied spinor index and add the contributions.
-//         onv.forEach([&value, &h, &g](const size_t p) {
-//             value += 2 * h(p, p);    // *2 because of seniority zero
-//             value += g(p, p, p, p);  // 1/2*2 because of seniority zero
-//         });
+        // Loop over every occupied spinor index and add the contributions.
+        onv.forEach([&value, &h, &g](const size_t p) {
+            value += 2 * h(p, p);    // *2 because of seniority zero
+            value += g(p, p, p, p);  // 1/2*2 because of seniority zero
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:274]:
```suggestion
            value += 2 * h(p, p);    // Factor *2 because of seniority zero.
            value += g(p, p, p, p);  // Factor 1/2*2 because of seniority zero.
```

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 7]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
+
+
+    // Initialize the resulting matrix-vector product from the diagonal contributions.
+    VectorX<double> matvec = this->evaluateOperatorDiagonal(hamiltonian).cwiseProduct(x);
+
+    // Create the first doubly-occupied ONV basis. Since in DOCI, alpha == beta, we can use the proxy ONV basis to treat them as one and multiply all contributions by 2.
     const auto proxy_onv_basis = this->proxy();
-    SpinUnresolvedONV onv = proxy_onv_basis.constructONVFromAddress(0);  // ONV with address 0
+    auto onv = proxy_onv_basis.constructONVFromAddress(0);  // ONV with address 0
+    for (size_t I = 0; I < dim; I++) {                      // I loops over all the addresses of the onv
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:336]:
```suggestion
    auto onv = proxy_onv_basis.constructONVFromAddress(0);  // ONV with address 0.
    for (size_t I = 0; I < dim; I++) {                      // I loops over all the addresses of the ONV.
```

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 8]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
 
-    for (size_t I = 0; I < dim; I++) {  // I loops over addresses of spin strings
+        // Using container values of type double reduce the number of times a vector has to be read from/written to
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:338]:
```suggestion
        // Using container values of type double reduce the number of times a vector has to be read from/written to.
```

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 9]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
+        double value = 0;
+        const double x_I = x(I);
 
-        callback(onv, I);
+        for (size_t e1 = 0; e1 < N_P; e1++) {            // e1 (electron 1) loops over the (number of) electrons
+            const size_t p = onv.occupationIndexOf(e1);  // retrieve the index of a given electron
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:343]:
```suggestion
        for (size_t e1 = 0; e1 < N_P; e1++) {            // E1 (electron 1) loops over the (number of) electrons.
            const size_t p = onv.occupationIndexOf(e1);  // Retrieve the index of a given electron.
```

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 10]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
 
-        if (I < dim - 1) {  // prevent the last permutation from occurring
+            // Remove the weight from the initial address I, because we annihilate
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:345]:
```suggestion
            // Remove the weight from the initial address I, because we annihilate.
```

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 11]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
+                matvec(J) += g(p, q, p, q) * x_I;
+
+                q++;  // go to the next orbital
+
+                // perform a shift  TODO: clarify what shift
+                proxy_onv_basis.shiftUntilNextUnoccupiedOrbital<1>(onv, address, q, e2);
+            }  // creation
+        }      // e1 loop (annihilation)
+
+        if (I < dim - 1) {  // prevent last permutation
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:369]:
```suggestion
            // Perform a shift.  TODO: clarify what shift.
            proxy_onv_basis.shiftUntilNextUnoccupiedOrbital<1>(onv, address, q, e2);

            while (q < K) {
                const size_t J = address + proxy_onv_basis.vertexWeight(q, e2);

                value += g(p, q, p, q) * x(J);
                matvec(J) += g(p, q, p, q) * x_I;

                q++;  // Go to the next orbital.

                // Perform a shift.  TODO: clarify what shift.
                proxy_onv_basis.shiftUntilNextUnoccupiedOrbital<1>(onv, address, q, e2);
            }  // Creation.
        }      // E1 loop (annihilation).

        if (I < dim - 1) {  // Prevent the last permutation.
```

File: gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp [hunk 12]
```diff
@@ -55,179 +57,323 @@ size_t SeniorityZeroONVBasis::calculateDimension(const size_t K, const size_t N_
...
             proxy_onv_basis.transformONVToNextPermutation(onv);
         }
+
+        matvec(I) += value;
     }  // address (I) loop
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp:374]:
```suggestion
    }  // Address (I) loop.
```

File: gqcp/src/ONVBasis/SpinResolvedONVBasis.cpp [hunk 13]
```diff
@@ -336,6 +360,57 @@ VectorX<double> SpinResolvedONVBasis::evaluateOperatorDiagonal(const RSQHamilton
...
+
+    // Calculate the diagonal contributions resulting from the two-electron on-site interactions by iterating over all ONVs.
+    VectorX<double> diagonal = VectorX<double>::Zero(this->dimension());
+
+    SpinUnresolvedONV onv_alpha = this->alpha().constructONVFromAddress(0);
+    SpinUnresolvedONV onv_beta = this->beta().constructONVFromAddress(0);
+    for (size_t Ia = 0; Ia < dim_alpha; Ia++) {  // Ia loops over the addresses of alpha ONVs
+        this->beta().transformONVCorrespondingToAddress(onv_beta, 0);
+
+        for (size_t Ib = 0; Ib < dim_beta; Ib++) {  // Ib loops over addresses of beta ONVs
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SpinResolvedONVBasis.cpp:391]:
```suggestion
    for (size_t Ia = 0; Ia < dim_alpha; Ia++) {  // Ia loops over the addresses of alpha ONVs.
        this->beta().transformONVCorrespondingToAddress(onv_beta, 0);

        for (size_t Ib = 0; Ib < dim_beta; Ib++) {  // Ib loops over addresses of beta ONVs.
```

File: gqcp/src/ONVBasis/SpinResolvedONVBasis.cpp [hunk 14]
```diff
@@ -336,6 +360,57 @@ VectorX<double> SpinResolvedONVBasis::evaluateOperatorDiagonal(const RSQHamilton
...
+
+            if (Ib < dim_beta - 1) {  // Prevent the last permutation from occurring.
+                this->beta().transformONVToNextPermutation(onv_beta);
+            }
+        }  // beta address (Ib) loop
+
+        if (Ia < dim_alpha - 1) {  // Prevent the last permutation from occurring.
+            this->alpha().transformONVToNextPermutation(onv_alpha);
+        }
+    }  // alpha address (Ia) loop
```
Comment (xdvriend) [inline gqcp/src/ONVBasis/SpinResolvedONVBasis.cpp:408]:
```suggestion
        }  // Beta address (Ib) loop.

        if (Ia < dim_alpha - 1) {  // Prevent the last permutation from occurring.
            this->alpha().transformONVToNextPermutation(onv_alpha);
        }
    }  // Alpha address (Ia) loop.
```

File: gqcp/tests/QCMethod/CI/DOCI_test.cpp [hunk 15]
```diff
@@ -1,312 +1,312 @@
...
 
-//     const double reference_energy = -14.8782216937;
+    const double reference_energy = -14.8782216937;
 
-//     // Read in the molecular Hamiltonian from a FCIDUMP file.
-//     const auto sq_hamiltonian = GQCP::RSQHamiltonian<double>::FromFCIDUMP("data/beh_cation_631g_caitlin.FCIDUMP");
-//     const auto K = sq_hamiltonian.numberOfOrbitals();  // the number of spatial orbitals
+    // Read in the molecular Hamiltonian from a FCIDUMP file.
+    const auto sq_hamiltonian = GQCP::RSQHamiltonian<double>::FromFCIDUMP("data/beh_cation_631g_caitlin.FCIDUMP");
+    const auto K = sq_hamiltonian.numberOfOrbitals();  // the number of spatial orbitals
```
Comment (xdvriend) [inline gqcp/tests/QCMethod/CI/DOCI_test.cpp:170]:
```suggestion
    const auto K = sq_hamiltonian.numberOfOrbitals();  // The number of spatial orbitals.
```

File: gqcp/tests/QCMethod/CI/Hubbard_test.cpp [hunk 16]
```diff
@@ -1,248 +1,248 @@
...
+         1, 0, 1, 0,
+         0, 1, 0, 1,
+         0, 0, 1, 0;
+    // clang-format on
 
-//     // Set the reference results
-//     const double t = 1.0;
-//     const std::vector<double> U_list {0.0, 1.0, 1.5, 3.5, 6.5, 9, 10};
-//     const std::vector<double> E_list {-4.472135955, -3.57536562, -3.202271824, -2.135871608, -1.338959715, -1.004379799, -0.9114974686};
+    // Set the reference results
```
Comment (xdvriend) [inline gqcp/tests/QCMethod/CI/Hubbard_test.cpp:112]:
```suggestion
    // Set the reference results.
```

File: gqcp/tests/QCMethod/CI/Hubbard_test.cpp [hunk 17]
```diff
@@ -1,248 +1,248 @@
...
-//     GQCP::SquareMatrix<double> A = GQCP::SquareMatrix<double>::Zero(K);
-//     // clang-format off
-//     A << 0, 1, 0, 0, 0, 1,
-//          1, 0, 1, 0, 0, 0,
-//          0, 1, 0, 1, 0, 0,
-//          0, 0, 1, 0, 1, 0,
-//          0, 0, 0, 1, 0, 1,
-//          1, 0, 0, 0, 1, 0;
-//     // clang-format on
+    // Create the adjacency matrix for a four-site chain
```
Comment (xdvriend) [inline gqcp/tests/QCMethod/CI/Hubbard_test.cpp:143]:
```suggestion
    // Create the adjacency matrix for a four-site chain.
```

File: gqcp/tests/QCMethod/CI/Hubbard_test.cpp [hunk 18]
```diff
@@ -1,248 +1,248 @@
...
+         0, 0, 0, 1, 0, 1,
+         1, 0, 0, 0, 1, 0;
+    // clang-format on
 
 
-//     // Set the reference results
-//     const double t = 1.0;
-//     const std::vector<double> U_list {0.0, 1.0, 1.5, 3.5, 6.5, 9, 10};
-//     const std::vector<double> E_list {-8, -6.601158293, -5.978815789, -4.025796251, -2.469458295, -1.836926909, -1.664362733};
+    // Set the reference results
```
Comment (xdvriend) [inline gqcp/tests/QCMethod/CI/Hubbard_test.cpp:157]:
```suggestion
    // Set the reference results.
```

**Review by xdvriend — APPROVED** [review]
Despite the number of comments, I believe this PR is almost good to go!

The comments I left are mostly punctuation and capitalisation in comments which I fixed in the suggestions. After applying those changes, I believe this PR may be merged. 😄

**Comment by lelemmen** [comment]
@xdvriend Thanks for taking the time to review this PR, and improve its punctuation!
