### PR TITLE
Spin expectation values

### LINKED ISSUE #474: 2RDM calculation failure
**Describe the bug**
2RDMs cannot be be calculated for systems where the number of alpha and beta electrons are not equal.

**To Reproduce**
Start an 2RDM calculation with a product Fock space with N_alpha ≠ N_beta.

**Screenshots and logs**
>Assertion failed: (index >= 0 && index < size()), function operator(), file /Users/tmhuysen/miniconda3/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h, line 180.

### PR DESCRIPTION
**Pull request by tmhuysen**
**Short description**

- [x] Adds the possibility to calculate expectation values for spin in the Z direction and spin squared

- [x] Fixes bug found in 2RDM calculations

**Related issues**
#215 (first step towards)
Fixes #474  (resolves the issue)

### CODE REVIEW

**Comment by lelemmen** [comment]
@tmhuysen Could you specify if the related issues will be fixed after merging this PR or not?

**Comment by lelemmen** [comment]
@tmhuysen Thanks for adding more information to the PR body. I've subsequently added "Fixes ..." to indicate that this PR will close the issue automatically.

File: gqcp/include/Processing/Properties/expectation_values.hpp [hunk 1]
```diff
@@ -89,6 +88,46 @@ std::array<double, Components> calculateExpectationValue(const SQTwoElectronOper
...
+        }
+    }
+    return s_squared;
+}
+
+
+/**
+ *  Calculate the expectation value for spin in the z direction
+ * 
+ *  @tparam Scalar      the scalar type
```
Comment (lelemmen) [inline gqcp/include/Processing/Properties/expectation_values.hpp]: idem

File: gqcp/include/Processing/Properties/expectation_values.hpp [hunk 2]
```diff
@@ -89,6 +88,46 @@ std::array<double, Components> calculateExpectationValue(const SQTwoElectronOper
...
+    double s_squared = -sz;
+    size_t K = one_rdms.one_rdm.dimension();
+    for (size_t p = 0; p < K; p++) {
+        s_squared += one_rdms.one_rdm_aa(p, p) + (one_rdms.one_rdm_aa(p, p) +  one_rdms.one_rdm_bb(p, p))/4;
+        for (size_t q = 0; q < K; q++) {
+            s_squared += -two_rdms.two_rdm_aabb(p,q,q,p);
+            s_squared += (two_rdms.two_rdm_aaaa(p,p,q,q) + two_rdms.two_rdm_bbbb(p,p,q,q) - two_rdms.two_rdm_aabb(p,p,q,q) - two_rdms.two_rdm_bbaa(p,p,q,q))/4;
+        }
+    }
+    return s_squared;
```
Comment (lelemmen) [inline gqcp/include/Processing/Properties/expectation_values.hpp]: Are you calculating S^2 using S+S-, S_z^2 and S_z? If you are, could you indicate which portions of the code correspond to it?

File: gqcp/include/Processing/Properties/expectation_values.hpp [hunk 3]
```diff
@@ -89,6 +88,46 @@ std::array<double, Components> calculateExpectationValue(const SQTwoElectronOper
...
+ *  @param one_rdms        all the one electron density matrices
+ *  @param two_rdms        all the two electron density matrices
+ *
+ *  @return expectation value of spin squared
+ */
+template <typename Scalar>
+double calculateSpinSquared(const OneRDMs<Scalar>& one_rdms, const TwoRDMs<Scalar>& two_rdms) {
+    double sz = calculateSpinZ(one_rdms);
+    double s_squared = -sz;
+    size_t K = one_rdms.one_rdm.dimension();
```
Comment (lelemmen) [inline gqcp/include/Processing/Properties/expectation_values.hpp]: const
```suggestion
    const size_t K = one_rdms.one_rdm.dimension();
```

Comment (lelemmen) [reply gqcp/include/Processing/Properties/expectation_values.hpp]: Also, could you provide the implementation of `OneRDMs.dimension()` and check the whole library for these occurrences?

File: gqcp/include/Processing/Properties/expectation_values.hpp [hunk 4]
```diff
@@ -89,6 +88,46 @@ std::array<double, Components> calculateExpectationValue(const SQTwoElectronOper
 }
 
 
+/**
+ *  Calculate the expectation value for spin squared
+ * 
+ *  @tparam Scalar      the scalar type
```
Comment (lelemmen) [inline gqcp/include/Processing/Properties/expectation_values.hpp]:
```suggestion
 *  @tparam Scalar      the scalar type of the density matrices
```

File: gqcp/include/Processing/Properties/expectation_values.hpp [hunk 5]
```diff
@@ -89,6 +88,46 @@ std::array<double, Components> calculateExpectationValue(const SQTwoElectronOper
...
+ * 
+ *  @param one_rdms        all the one electron density matrices
```
Comment (lelemmen) [inline gqcp/include/Processing/Properties/expectation_values.hpp]:
```suggestion
 *  @param one_rdms        all the one-electron density matrices
```

File: gqcp/include/Processing/Properties/expectation_values.hpp [hunk 6]
```diff
@@ -89,6 +88,46 @@ std::array<double, Components> calculateExpectationValue(const SQTwoElectronOper
...
+ *  @param two_rdms        all the two electron density matrices
```
Comment (lelemmen) [inline gqcp/include/Processing/Properties/expectation_values.hpp]:
```suggestion
 *  @param two_rdms        all the two-electron density matrices
```

File: gqcp/include/Processing/Properties/expectation_values.hpp [hunk 7]
```diff
@@ -89,6 +88,46 @@ std::array<double, Components> calculateExpectationValue(const SQTwoElectronOper
 }
 
 
+/**
+ *  Calculate the expectation value for spin squared
```
Comment (lelemmen) [inline gqcp/include/Processing/Properties/expectation_values.hpp]:
```suggestion
 *  Calculate the expectation value of the square of the spin angular momentum operator
```

File: gqcp/include/Processing/Properties/expectation_values.hpp [hunk 8]
```diff
@@ -89,6 +88,46 @@ std::array<double, Components> calculateExpectationValue(const SQTwoElectronOper
...
+ * 
+ *  @tparam Scalar      the scalar type
+ * 
+ *  @param one_rdms        all the one electron density matrices
+ *  @param two_rdms        all the two electron density matrices
+ *
+ *  @return expectation value of spin squared
```
Comment (lelemmen) [inline gqcp/include/Processing/Properties/expectation_values.hpp]:
```suggestion
 *  @return the expectation value of the square of the spin angular momentum operator
```

File: gqcp/include/Processing/Properties/expectation_values.hpp [hunk 9]
```diff
@@ -89,6 +88,46 @@ std::array<double, Components> calculateExpectationValue(const SQTwoElectronOper
...
+            s_squared += -two_rdms.two_rdm_aabb(p,q,q,p);
+            s_squared += (two_rdms.two_rdm_aaaa(p,p,q,q) + two_rdms.two_rdm_bbbb(p,p,q,q) - two_rdms.two_rdm_aabb(p,p,q,q) - two_rdms.two_rdm_bbaa(p,p,q,q))/4;
+        }
+    }
+    return s_squared;
+}
+
+
+/**
+ *  Calculate the expectation value for spin in the z direction
```
Comment (lelemmen) [inline gqcp/include/Processing/Properties/expectation_values.hpp]:
```suggestion
 *  Calculate the expectation value of the z-component of the spin angular momentum operator
```

File: gqcp/include/Processing/Properties/expectation_values.hpp [hunk 10]
```diff
@@ -89,6 +88,46 @@ std::array<double, Components> calculateExpectationValue(const SQTwoElectronOper
...
+ * 
+ *  @tparam Scalar      the scalar type
+ * 
+ *  @param one_rdms        all the one electron density matrices
```
Comment (lelemmen) [inline gqcp/include/Processing/Properties/expectation_values.hpp]:
```suggestion
 *  @param one_rdms        all the one-electron density matrices
```

File: gqcp/include/Processing/RDM/RDMs.hpp [hunk 11]
```diff
@@ -65,6 +65,10 @@ struct OneRDMs {
         one_rdm_aa (one_rdm_aa),
         one_rdm_bb (one_rdm_bb)
     {}
+
+    OneRDM<Scalar> spinDensityRDM() const {
```
Comment (lelemmen) [inline gqcp/include/Processing/RDM/RDMs.hpp]: Provide documentation.

File: gqcp/src/QCMethod/Applications/FCI.cpp [hunk 12]
```diff
@@ -104,6 +107,13 @@ void FCI::solve() {
     double internuclear_repulsion_energy = Operator::NuclearRepulsion(molecule).value();
 
     this->energy_solution = fci_energy + internuclear_repulsion_energy;
+
+    RDMCalculator rdm_calculator(fci_solver.makeWavefunction());
```
Comment (lelemmen) [inline gqcp/src/QCMethod/Applications/FCI.cpp]:
```suggestion
    RDMCalculator rdm_calculator (fci_solver.makeWavefunction());
```

File: gqcp/include/QCMethod/Applications/FCI.hpp [hunk 13]
```diff
@@ -77,6 +78,11 @@ class FCI {
      *  @return the ground state FCI energy
      */
     double energy() const;
+
+    /**
+     *  @return the spin squared expectation value of the ground state
```
Comment (lelemmen) [inline gqcp/include/QCMethod/Applications/FCI.hpp]:
```suggestion
     *  @return the expectation value of the square of the spin angular momentum operator of the ground state
```

File: gqcp/src/QCMethod/Applications/FCI.cpp [hunk 14]
```diff
@@ -120,5 +130,18 @@ double FCI::energy() const {
 }
 
 
+/**
+ *  @return the spin squared expectation value of the ground state
```
Comment (lelemmen) [inline gqcp/src/QCMethod/Applications/FCI.cpp]:
```suggestion
 *  @return the expectation value of the square of the spin angular momentum operator of the ground state
```

File: gqcp/src/QCMethod/Applications/FCI.cpp [hunk 15]
```diff
@@ -120,5 +130,18 @@ double FCI::energy() const {
...
+ */
+double FCI::spinSquared() const {
+
+    if (this->is_solved) {
+        return this->s_squared;
+    } else {
+        throw std::runtime_error("FCI::spinSquared(): You are trying to get spin squared but the method hasn't been solved yet.");
```
Comment (lelemmen) [inline gqcp/src/QCMethod/Applications/FCI.cpp]:
```suggestion
        throw std::runtime_error("FCI::spinSquared(): You are trying to get the expectation value of S^2 of the ground state but the method hasn't been solved yet.");
```

File: gqcp/tests/Processing/Properties/expectation_values_test.cpp [hunk 16]
```diff
@@ -195,3 +195,48 @@ BOOST_AUTO_TEST_CASE ( S_z_constrained_NOplus_STO_3G ) {
     // Check that the Sz for a single fragment has changed
     BOOST_CHECK(std::abs(N_Sz) > 1.0e-06);
 }
+
```
Comment (lelemmen) [inline gqcp/tests/Processing/Properties/expectation_values_test.cpp]:
```suggestion


```

File: gqcp/tests/Processing/Properties/expectation_values_test.cpp [hunk 17]
```diff
@@ -195,3 +195,48 @@ BOOST_AUTO_TEST_CASE ( S_z_constrained_NOplus_STO_3G ) {
...
+/*
+ *  Calculate the Sz and S-squared values for oxygen gas
```
Comment (lelemmen) [inline gqcp/tests/Processing/Properties/expectation_values_test.cpp]:
```suggestion
 *  Calculate Sz and S^2 values for O2 in a restricted Fock space (alpha == beta)
```

File: gqcp/tests/Processing/Properties/expectation_values_test.cpp [hunk 18]
```diff
@@ -195,3 +195,48 @@ BOOST_AUTO_TEST_CASE ( S_z_constrained_NOplus_STO_3G ) {
...
+    
+    GQCP::OneRDMs<double> one_rdms = rdm_calculator.calculate1RDMs();
+    GQCP::TwoRDMs<double> two_rdms = rdm_calculator.calculate2RDMs();
+    
+    double s_squared = GQCP::calculateSpinSquared<double>(one_rdms, two_rdms);
+    double s_z = GQCP::calculateSpinZ<double>(one_rdms);
+
+    // Spin squared should be 2 (S=1)
+    BOOST_CHECK(std::abs(s_squared - 2) < 1.0e-06);
+    // We've applied have alpha = beta, hence spin in the z direction is 0
```
Comment (lelemmen) [inline gqcp/tests/Processing/Properties/expectation_values_test.cpp]:
```suggestion

    // In the restricted Fock space, alpha = beta, hence the expectation value of the z-component of the spin operator should be zero
```

File: gqcp/tests/Processing/Properties/expectation_values_test.cpp [hunk 19]
```diff
@@ -195,3 +195,48 @@ BOOST_AUTO_TEST_CASE ( S_z_constrained_NOplus_STO_3G ) {
...
+    
+    GQCP::RDMCalculator rdm_calculator (ci_solver.makeWavefunction());
+    
+    GQCP::OneRDMs<double> one_rdms = rdm_calculator.calculate1RDMs();
+    GQCP::TwoRDMs<double> two_rdms = rdm_calculator.calculate2RDMs();
+    
+    double s_squared = GQCP::calculateSpinSquared<double>(one_rdms, two_rdms);
+    double s_z = GQCP::calculateSpinZ<double>(one_rdms);
+
+    // Spin squared should be 2 (S=1)
```
Comment (lelemmen) [inline gqcp/tests/Processing/Properties/expectation_values_test.cpp]:
```suggestion
    // <S^2> should be 2 (S=1)
```

Plus, could you mention why this is the case?

File: gqcp/tests/Processing/RDM/FCIRDMBuilder_test.cpp [hunk 20]
```diff
@@ -223,3 +223,49 @@ BOOST_AUTO_TEST_CASE ( throw_calculate_element ) {
     GQCP::FCIRDMBuilder fci_rdm (fock_space);
     BOOST_CHECK_THROW(fci_rdm.calculateElement({0,0,1}, {1,0,2}, coeff), std::runtime_error);
 }
+
+
+/*
+ *  Compare RDMs from product Fock space and selected Fock space (expandend in the full product Fock space)
```
Comment (lelemmen) [inline gqcp/tests/Processing/RDM/FCIRDMBuilder_test.cpp]:
```suggestion
 *  Compare the RDMs calculated from a product Fock space and an equivalent selected Fock space
```

File: gqcpy/src/QCMethod/Applications/FCI.cpp [hunk 21]
```diff
@@ -36,7 +36,9 @@ void bindQCMethodFCI(py::module& module) {
 
         .def("solve", &GQCP::QCMethod::FCI::solve, "Solve the eigenvalue equations such that the lowest energy and corresponding eigenvector become available. ")
 
-        .def("get_energy", &GQCP::QCMethod::FCI::energy, "Get the lowest energy.");
+        .def("get_energy", &GQCP::QCMethod::FCI::energy, "Get the lowest energy.")
+
+        .def("get_spin_squared", &GQCP::QCMethod::FCI::spinSquared, "Get spin squared of the groundstate.");
```
Comment (lelemmen) [inline gqcpy/src/QCMethod/Applications/FCI.cpp]:
```suggestion
        .def("get_spin_squared", &GQCP::QCMethod::FCI::spinSquared, "Get <S^2> of the groundstate.");
```

File: gqcpy/tests/QCMethod/Applications/FCI_test.py [hunk 22]
```diff
@@ -23,9 +23,10 @@ def tearDown(self):
         pass
 
 
-    def test_energies(self):
-        """Compare the energy with a reference value"""
+    def test_solution(self):
+        """Compare the energy and spin squared with a reference value"""
```
Comment (lelemmen) [inline gqcpy/tests/QCMethod/Applications/FCI_test.py]:
```suggestion
        """Compare the energy and <S^2> with a reference value"""
```

File: gqcpy/tests/QCMethod/Applications/FCI_test.py [hunk 23]
```diff
@@ -23,9 +23,10 @@ def tearDown(self):
...
         self.assertAlmostEqual(self.fci_module.get_energy(), self.ref_energy)
+        self.assertAlmostEqual(self.fci_module.get_spin_squared(), 0)
```
Comment (lelemmen) [inline gqcpy/tests/QCMethod/Applications/FCI_test.py]: Could you mention why you expect $0$?

File: gqcp/include/Processing/Properties/expectation_values.hpp (hunk 3 above)
Comment (tmhuysen) [reply gqcp/include/Processing/Properties/expectation_values.hpp]: I do not understand the request.

Comment (lelemmen) [reply gqcp/include/Processing/Properties/expectation_values.hpp]: `OneRDM` has a method called `dimension()`, could you implement `dimension()` for `OneRDMs` too?

File: gqcp/include/Processing/RDM/RDMs.hpp [hunk 24]
```diff
@@ -65,6 +65,17 @@ struct OneRDMs {
...
+
+    /**
+     *  @return the difference between the alpha and beta 1-RDM
+     */ 
+    OneRDM<Scalar> spinDensityRDM() const {
+        return one_rdm_aa - one_rdm_bb;
+    }
+
+    
+    size_t dimension() const { return one_rdm.dimension(); }
```
Comment (lelemmen) [inline gqcp/include/Processing/RDM/RDMs.hpp]: Add documentation.

File: gqcp/include/Processing/RDM/RDMs.hpp [hunk 25]
```diff
@@ -102,6 +113,9 @@ struct TwoRDMs {
         two_rdm_bbaa (two_rdm_bbaa),
         two_rdm_bbbb (two_rdm_bbbb)
     {}
+
+
+    size_t dimension() const { return two_rdm.dimension(); }
```
Comment (lelemmen) [inline gqcp/include/Processing/RDM/RDMs.hpp]: Add documentation.

File: gqcp/tests/Processing/Properties/expectation_values_test.cpp [hunk 26]
```diff
@@ -195,3 +195,50 @@ BOOST_AUTO_TEST_CASE ( S_z_constrained_NOplus_STO_3G ) {
...
+    
+    GQCP::RDMCalculator rdm_calculator (ci_solver.makeWavefunction());
+    
+    GQCP::OneRDMs<double> one_rdms = rdm_calculator.calculate1RDMs();
+    GQCP::TwoRDMs<double> two_rdms = rdm_calculator.calculate2RDMs();
+    
+    double s_squared = GQCP::calculateSpinSquared<double>(one_rdms, two_rdms);
+    double s_z = GQCP::calculateSpinZ<double>(one_rdms);
+
+    // <S^2> should be 2 (S=1)
```
Comment (lelemmen) [inline gqcp/tests/Processing/Properties/expectation_values_test.cpp]:
```suggestion
    // <S^2> should be 2 (S=1) because the ground state for O2 is a biradical triplet.
```

File: gqcp/tests/Processing/RDM/FCIRDMBuilder_test.cpp [hunk 27]
```diff
@@ -174,7 +174,7 @@ BOOST_AUTO_TEST_CASE ( H2O_energy_RDM_contraction_FCI ) {
 
 BOOST_AUTO_TEST_CASE ( H2O_energy_RDM_contraction_FCI_wavefunction ) {
 
-    // repeat contraction with wavefunction input (and RDMCalculator API
+    // repeat contraction with wavefunction input (and RDMCalculator API)
```
Comment (lelemmen) [inline gqcp/tests/Processing/RDM/FCIRDMBuilder_test.cpp]:
```suggestion
    // Repeat the contraction with an FCI wave function as input and the RDMCalculator API.
```

**Comment by lelemmen** [comment]
@tmhuysen Also, another general remark: could you make sure to give a more enlightening description to your commits? Thanks!
